### ISSUE TITLE
Export the age of my money

### ISSUE THREAD

**Issue by grahamc** [hoenn/ynab-metrics#1]
I'd like to create a metric for the money's age. This seems workable without too much trouble:

```console
$ curl \
  -X GET \
  "https://api.youneedabudget.com/v1/budgets/xxx/months/current" \
  -H  "accept: application/json" \
  -H  "Authorization: Bearer xxx" \
| jq .data.month.age_of_money
24
```

I'm not familiar with your project, but I know a little bit of Go. Do you have any pointers on implementing this?

Thanks!

**Comment by hoenn** [comment]
@grahamc 👋 

It looks like it would be pretty easy to access age of money already.

In main.go [we retrieve `[]*budget.Budget`](https://github.com/hoenn/ynab-metrics/blob/be340c31fc057fba7d568c72954f8deacdb38920/main.go#L34)

From there we call some functions that set gauges for accounts, categories, and transactions which all use that list of budgets. Looking at the `budget.Budget` type from the go ynab client I'm using in comparison to your `curl` request:

```go
// Budget represents a budget
type Budget struct {
        ...
	Months                   []*month.Month                         `json:"months"`

``` 

and looking at `*month.Month`

```go
// Month represents a month for a budget
// Each budget contains one or more months, which is where To be Budgeted,
// Age of Money and Category (budgeted / activity / balances)
// amounts are available.
type Month struct {
        ...
	AgeOfMoney   *int64  `json:"age_of_money"`
}
```

we can find the age of money data you're looking for.

That should be enough to get started. I haven't worked on this project for awhile so I'll probably recommend a fork for a new feature.

[Reference to the go YNAB library](https://pkg.go.dev/go.bmvs.io/ynab@v1.3.0/api/budget#Budget)
