### ISSUE TITLE
Error when running `make build`

### ISSUE THREAD

**Issue by Miodec** [hoenn/ynab-metrics#3]
I'm getting this error when trying to run `make build` on MacOS 13.4. I have already created a `config.json` file and inserted my access token.
<img width="379" alt="image" src="https://github.com/hoenn/ynab-metrics/assets/13181393/1f1eb619-debc-4557-922d-ef32cc6af16f">

**Comment by hoenn** [comment]
Hey @Miodec can you try removing [these lines](https://github.com/hoenn/ynab-metrics/blob/master/Makefile#L6-L7) and see if you can proceed? It seems they are unused anyway.

**Comment by Miodec** [comment]
`build` ran, but this time during `run` im getting:

```
./target/ynab-metrics --config config.json
panic: Could not unmarshal config file

goroutine 1 [running]:
github.com/hoenn/ynab-metrics/pkg/config.ParseConfig({0x16f52b787?, 0x1400001e1c0?})
	/Users/_/documents/code/ynab-metrics/pkg/config/config.go:23 +0xf0
main.main()
	/Users/_/documents/code/ynab-metrics/main.go:25 +0x74
make: *** [run] Error 2
```

**Comment by hoenn** [comment]
So the unmarshal errors are related to the format of the `config.json` which is probably based on my `sample-config.json`. That config is not formatted correctly and you can update it for now like this:
```json
{
    "port": "8080",
    "include_transactions": true,
    "access_token": "z02f...youraccesstoken...2e7",
    "interval_seconds": 90
}
```

Notice that `"port"` is now a string and `"user_token"` has been renamed to `"access_token"`, this is what is expected from the json unmarshal
```
//Config represents the configuration for the exporter
type Config struct {
	Port            string `json:"port"`
	GetTrans        bool   `json:"include_transactions"`
	AccessToken     string `json:"access_token"`
	IntervalSeconds uint64 `json:"interval_seconds"`
}
```

**Comment by Miodec** [comment]
Now we're cookin

<img width="440" alt="image" src="https://github.com/hoenn/ynab-metrics/assets/13181393/a2cece71-9fa1-4bde-8bf5-3a4d9ea58066">


All though going to `localhost:8080` gives me a `404` 🤔

**Comment by hoenn** [comment]
Well port 8080 is looking prometheus, do you have that running locally?

**Comment by Miodec** [comment]
Ah, its `http://localhost:8080/metrics`, looks like we are all good!

**Comment by hoenn** [comment]
Sorry my last message was misleading anyway :P you got it!

**Comment by hoenn** [comment]
If you're interested you can submit a PR to fix these issues you found:
- sample-config.json has the wrong format and is misleading (though the README example seems correct)
- Remove TOKEN and TOKENFILE from Makefile because they're unused.

If not I can fix these later on

**Comment by Miodec** [comment]
I'll leave that up to you - I'm gonna play around with some Grafana now haha. Thanks for the help!
